spring.application.name=url-shortener-sb

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
#spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=f6b65fd46fca78f8
jwt.expiration=172800000